### ISSUE TITLE
ROM source code

### ISSUE THREAD

**Issue by rosco-pc** [parallaxinc/propeller#10]
Can I suggest to place the ROM source code somewhere in the parallax github repo? 
Currently they are attachments in the forum and might get lost there.

I feel that those do not really belong in the P2 example section, otherwise I would submit a pull request for that :)

**Comment by PropGit** [comment]
Yes, I agree.  I'll craft a place for it and will update the links accordingly.

**Comment by rosco-pc** [comment]
I actually see that the P2 rom v32i source is located in the example code. Sorry did not see that before

**Comment by rosco-pc** [comment]
As it is already at a 'pre-defined' place I propose to close this one
