### ISSUE TITLE
test_LEDMATRIX.spin2 Missing () After Main

### ISSUE THREAD

**Issue by cjmoorejr** [parallaxinc/propeller#184]
PNut v34z is complaining about missing '(' after PUB Main.  I changed PUB Main to PUB Main() and PNut stopped complaining.

**Comment by PropGit** [comment]
Thank you @cjmoorejr.  Fixed in commit [c30d635](https://github.com/parallaxinc/propeller/commit/c30d63518d6b1cac1c1ec835a8e93acc33c092e5)
