### ISSUE TITLE
test_LEDMATRIX Error in OBJ Section

### ISSUE THREAD

**Issue by cjmoorejr** [parallaxinc/propeller#185]
Under propeller/resources/Accessory Test Code/

File test_LEDMATRIX has an error in OBJ section.  PNut v34z is complaining "Cannot find .spin2 or .obj file for Pins.spin2".

OBJ section contains:

pins:  "Pins.spin2"

I modified above to:

pins:  "Pins"

PNut stopped complaining.

**Comment by PropGit** [comment]
Thank you @cjmoorejr.  Fixed in commit [c30d635](https://github.com/parallaxinc/propeller/commit/c30d63518d6b1cac1c1ec835a8e93acc33c092e5)

Removed OBJ reference since all can be done with single-line Spin2 features.
