### ISSUE TITLE
Waitcnt & cnt Not in SPIN2

### ISSUE THREAD

**Issue by cjmoorejr** [parallaxinc/propeller#186]
In file propeller/resources/Accessory Test Code/Pins.spin2

PNut v34z complained about the following code:

waitcnt(clkfreq / 10000 + cnt)  

with "Expected an instruction or variable"

I had to modify the code as follows:

waitct(clkfreq / 10000 * getct())

This occurred at 2 locations in the file.

**Comment by PropGit** [comment]
Thank you @cjmoorejr.  Fixed in commit [c30d635](https://github.com/parallaxinc/propeller/commit/c30d63518d6b1cac1c1ec835a8e93acc33c092e5)
