### ISSUE TITLE
New DS1302 Driver for P2 (converted from P1 OBEX source)

### ISSUE THREAD

**Issue by dgately** [parallaxinc/propeller#211]
I've converted DS1302_full.spin from the old OBEX to DS1302_full.spin2. This code compiles on PropTool 2.4.1 for P2 as well as in flexprop (version 5.0.5 beta). A demo/example is included in the .zip archive.

[DS1302_full.zip](https://github.com/parallaxinc/propeller/files/5763057/DS1302_full.zip)

**Comment by PropGit** [comment]
Thanks @dgately - I started the steps to include your object, but noticed that the DS1302_full.spin2 source still appears the way you reported over the weekend; with certain characters garbled.

We're you able to create a version that looks the way you intended?  Do you need help in fixing it?

I checked the file and it appears it was saved in ANSI format (there's no BOM header at the start indicating its UTF-16) and I manually edited the file to insert the BOM header on the hunch that all would be well, but it didn't totally resolve the problem.

**Comment by dgately** [comment]
OK... I'll try again.

I zipped the folder on WIN10 this time, instead of copying it over to macOS:
[DS1302.zip](https://github.com/parallaxinc/propeller/files/5766713/DS1302.zip)

**Comment by PropGit** [comment]
That fixed it.  It will be posted soon.

**Comment by PropGit** [comment]
Posted in [commit](https://github.com/parallaxinc/propeller/commit/159570e66d684daad395017f703a7999b506e224).  Linked from [Recent Activity](https://propeller.parallax.com/p2.html#recent-activity) also.
