### ISSUE TITLE
Getting a .spin version of code found on Gethub.

### ISSUE THREAD

**Issue by rkennelley** [parallaxinc/propeller#260]
I was looking for real time clock code I could use with a Parallax Propeller One which I found here:

https://github.com/parallaxinc/propeller/tree/master/libraries/community/p1/All/DS1307%20RTC%20Driver

The problem is the code is in some kind of an editor that is difficult and time consuming to extract from. When I'm done  I still  need to do the same with any support files (OBJ files). Is there a way to generate .spin files I can load up in my programing utility to run or edit?

I'm thinking there must be a way to make this task more easy to do on your website. Can you help me?

I'm new to Gethub and still getting started with your website. 

Thank You in advance.

Bob

**Comment by PropGit** [comment]
Hi Bob.  Thank you for contacting us.  I think the problem you're referring to is that GitHub doesn't let you easily download a zip file of a single object entry.  This has been a problem we've recognized and are working to resolve.

We are currently transitioning to a new website that supports Propeller Objects in a better manner that GitHub.  You can access this object by going to hub.parallax.com, selecting the search field, and typing "DS1307".  I've provided the direct link for you here:

https://hub.parallax.com/obex/ds1307-rtc-driver/

Just click on the download link to retrieve a ZIP archive of all the files in that submitted object.
